# Generated by Django 4.2.3 on 2023-07-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_field',
            field=models.CharField(blank=True, default='extra field', max_length=200, null=True),
        ),
    ]
